import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SingleToast from "./components/singleToast/singleToast";
import "./globals.css";
import { ProviderInjector } from "./redux/userInfo/storageInjector";
import { useDispatch } from "react-redux";
// singleToast

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderInjector>
          <SingleToastInject>{children}</SingleToastInject>
        </ProviderInjector>
      </body>
    </html>
  );
}

interface SingleToastInjectProps {
  children: React.ReactNode;
}
function SingleToastInject(props: SingleToastInjectProps) {


  return <SingleToast>{props.children}</SingleToast>;
}
